---
# Мастер-плейбук

- name: Install webservers
  import_playbook: nginx.yaml
  tags: nginx

- name: Install node and nginx exporters
  import_playbook: exporters.yaml
  tags: exporter

- name: Install prometheus
  import_playbook: prometheus.yaml
  tags: prometheus

- name: Install grafana
  import_playbook: grafana-full.yaml
  tags: grafana
