---
# Мастер-плейбук

- name: Install webservers
  import_playbook: nginx.yaml

- name: Install node and nginx exporters
  import_playbook: exporters.yaml

- name: Install prometheus
  import_playbook: prometheus.yaml

- name: Install grafana
  import_playbook: grafana.yaml

- name: Install grafana dashboards
  import_playbook: grafana_dashboards.yaml