---
# Мастер-плейбук

- name: Install webservers
  import_playbook: nginx.yaml
  tags: nginx

- name: Install node and nginx exporters
  import_playbook: exporters.yaml
  tags: exporter

- name: Install prometheus
  import_playbook: prometheus.yaml
  tags: prometheus

- name: Install grafana
  import_playbook: grafana-full.yaml
  tags: grafana

- name: Install elasticsearch
  import_playbook: es.yaml
  tags: elasticsearch

- name: Install kibana
  import_playbook: kibana.yaml
  tags: kibana

- name: Install filebeat
  import_playbook: filebeat.yaml
  tags: filebeat